---
driver:
  name: vagrant

platforms:
  - name: ubuntu-14.04
    driver_config:
      box: opscode_ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[influxdb::default]
    attributes:
      influxdb:
        version: "0.8.8"
        action: ['create', 'start']
  - name: zero_nine
    run_list:
      - recipe[apt::default]
      - recipe[influxdb::default]
    attributes:
      influxdb:
        version: "0.9.0"
        action: ['create', 'start']
